spring:
  datasource:
    url: jdbc:postgresql://localhost/demo
    driverClassName: org.postgresql.Driver
    username: demo
    password: demo
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
  shedlock:
    defaultLockAtMostFor: 20m
    name: demo

setting:
  service:
    internal:
      name: Demo
      key: yukiii
  cron:
    expression: '0 0/10 * * * ?'
    zone: 'GMT+7'